//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#include <noz/noz.h>
#include "game_assets.h"


// @Shader
Shader* SHADER_VFX = nullptr;
Shader* SHADER_UI_VIGNETTE = nullptr;
Shader* SHADER_UI = nullptr;
Shader* SHADER_TEXT = nullptr;
Shader* SHADER_LIT = nullptr;

// @name

// @path
const Name* PATH_SHADER_VFX = nullptr;
const Name* PATH_SHADER_UI_VIGNETTE = nullptr;
const Name* PATH_SHADER_UI = nullptr;
const Name* PATH_SHADER_TEXT = nullptr;
const Name* PATH_SHADER_LIT = nullptr;

// @load
bool LoadAssets(Allocator* allocator)
{
    // @name

    // @path
    PATH_SHADER_VFX = GetName("vfx");
    PATH_SHADER_UI_VIGNETTE = GetName("ui_vignette");
    PATH_SHADER_UI = GetName("ui");
    PATH_SHADER_TEXT = GetName("text");
    PATH_SHADER_LIT = GetName("lit");

    // @Shader
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_VFX, SHADER_VFX);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI_VIGNETTE, SHADER_UI_VIGNETTE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI, SHADER_UI);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_TEXT, SHADER_TEXT);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_LIT, SHADER_LIT);

    static Shader* _SHADER[] = {
        SHADER_VFX,
        SHADER_UI_VIGNETTE,
        SHADER_UI,
        SHADER_TEXT,
        SHADER_LIT,
        nullptr
    };

    SHADER = _SHADER;

    return true;
}

// @unload
void UnloadAssets()
{
    // @Shader
    Free(SHADER_VFX);
    Free(SHADER_UI_VIGNETTE);
    Free(SHADER_UI);
    Free(SHADER_TEXT);
    Free(SHADER_LIT);
}

#ifdef NOZ_EDITOR

void HotloadAsset(const Name* incoming_name, AssetSignature incoming_signature)
{
    // @Shader
    NOZ_RELOAD_SHADER(PATH_SHADER_VFX, SHADER_VFX);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI_VIGNETTE, SHADER_UI_VIGNETTE);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI, SHADER_UI);
    NOZ_RELOAD_SHADER(PATH_SHADER_TEXT, SHADER_TEXT);
    NOZ_RELOAD_SHADER(PATH_SHADER_LIT, SHADER_LIT);
}

#endif // NOZ_EDITOR
