//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#pragma once

#include <noz/core_assets.h>

// @Animation
extern Animation* ANIMATION_HUMAN_IDLE;
extern Animation* ANIMATION_ARCHER_IDLE;
extern Animation* ANIMATION_ARCHER_DRAW;

// @Font
extern Font* FONT_SEGUISB;

// @Vfx
extern Vfx* VFX_ARROW_HIT;

// @Mesh
extern Mesh* MESH_WEAPON_BOW;
extern Mesh* MESH_TOWER_PLAYER_TEMP;
extern Mesh* MESH_PROJECTILE_ARROW;
extern Mesh* MESH_ICON_FIGHT;
extern Mesh* MESH_HUMAN_LEG_R;
extern Mesh* MESH_HUMAN_LEG_L;
extern Mesh* MESH_HUMAN_HEAD;
extern Mesh* MESH_HUMAN_HAND;
extern Mesh* MESH_HUMAN_FOOT_R;
extern Mesh* MESH_HUMAN_FOOT_L;
extern Mesh* MESH_HUMAN_EYE;
extern Mesh* MESH_HUMAN_BODY;
extern Mesh* MESH_ARCHER_HEAD;
extern Mesh* MESH_ARCHER_BODY;

// @Shader
extern Shader* SHADER_VFX;
extern Shader* SHADER_UI_VIGNETTE;
extern Shader* SHADER_UI;
extern Shader* SHADER_TEXT;
extern Shader* SHADER_LIT;
extern Shader* SHADER_VIGNETTE;
extern Shader* SHADER_SHADOW;

// @Skeleton
extern Skeleton* SKELETON_HUMAN;
extern Skeleton* SKELETON_ARCHER;

// @Texture
extern Texture* TEXTURE_PALETTE_RED;
extern Texture* TEXTURE_PALETTE;

// @name
extern const Name* NAME_ROOT;
extern const Name* NAME_BODY;
extern const Name* NAME_LEG_R;
extern const Name* NAME_BONE;
extern const Name* NAME_LEG_L;
extern const Name* NAME_LOOK;
extern const Name* NAME_HEAD;
extern const Name* NAME_FOOT_R;
extern const Name* NAME_FOOT_L;
extern const Name* NAME_EYE_L;
extern const Name* NAME_EYE_R;
extern const Name* NAME_HAND_R;
extern const Name* NAME_HAND_L;


// @BONE_ARCHER
constexpr int BONE_ARCHER_ROOT = 0;
constexpr int BONE_ARCHER_BODY = 1;
constexpr int BONE_ARCHER_LEG_R = 2;
constexpr int BONE_ARCHER_BONE = 3;
constexpr int BONE_ARCHER_LEG_L = 4;
constexpr int BONE_ARCHER_LOOK = 5;
constexpr int BONE_ARCHER_HEAD = 6;
constexpr int BONE_ARCHER_FOOT_R = 7;
constexpr int BONE_ARCHER_FOOT_L = 8;
constexpr int BONE_ARCHER_EYE_L = 9;
constexpr int BONE_ARCHER_EYE_R = 10;
constexpr int BONE_ARCHER_HAND_R = 11;
constexpr int BONE_ARCHER_HAND_L = 12;

// @BONE_HUMAN
constexpr int BONE_HUMAN_ROOT = 0;
constexpr int BONE_HUMAN_BODY = 1;
constexpr int BONE_HUMAN_LEG_R = 2;
constexpr int BONE_HUMAN_FOOT_R = 3;
constexpr int BONE_HUMAN_LEG_L = 4;
constexpr int BONE_HUMAN_FOOT_L = 5;
constexpr int BONE_HUMAN_HEAD = 6;
constexpr int BONE_HUMAN_HAND_L = 7;
constexpr int BONE_HUMAN_HAND_R = 8;
constexpr int BONE_HUMAN_EYE_R = 9;
constexpr int BONE_HUMAN_EYE_L = 10;
constexpr int BONE_HUMAN_BONE = 11;


extern bool LoadAssets(Allocator* allocator);
extern void UnloadAssets();

#ifdef NOZ_EDITOR
extern void HotloadAsset(const Name* incoming_name, AssetSignature incoming_signature);
#endif
